details:
    page_title: Velocity Dourges 2 Analytics
layout:
    - row_1_of_2:
        - col_1_of_3:
            - tile_template: matomo_widget
              tile_id: matomo_real_time_visits_ex
              title: Real Time Visits
              classes:
                -
        - col_1_of_3:
            - tile_template: matomo_widget
              tile_id: matomo_real_time_map_ex
              title: Real Time Map
              classes:
        - col_1_of_3:
            - tile_template: matomo_widget
              tile_id: matomo_velocity_profiles_ex
              title: Profiles
              classes:
    - row_1_of_2:
        - col_1_of_3:
            - tile_template: matomo_widget
              tile_id: matomo_velocity_error_ex
              title: Errors
              classes:
                -
        - col_1_of_3:
            - tile_template: matomo_widget
              tile_id: matomo_velocity_warning_ex
              title: Warning
              classes:
        - col_1_of_3:
            - tile_template: matomo_widget
              tile_id: matomo_velocity_disconnections_ex
              title: Disconnections
              classes:
        - col_1_of_4:
