apiVersion: v1
kind: ConfigMap
metadata:
  name: tipboard-configmap
  labels:
    app: tipboard
data:
  default_config.yaml: |
{{ .Files.Get "tipboard/default_config.yaml" | indent 4 }}
  settings-local.py: |
{{ .Files.Get "tipboard/settings-local.py" | indent 4 }}
