apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
spec:
  ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Values.app }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
