---
# Source: tipboard-ops/charts/commons/templates/01-dockerconfigjson-secret.yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: "dockerconfigjson-secret"
data:
  .dockerconfigjson: >-
    WW91clRva2VuSGVyZQ==
