---
# Source: tipboard-ops/charts/tipboard/templates/05-python3-tipboard-route.yaml

apiVersion: v1
kind: Route
metadata:
  name: tipboard
  labels:
    app: tipboard
spec:
  host: tipboard
  port:
    targetPort: 8080
  to:
    kind: Service
    name: tipboard
    weight: null
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge